In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pyreadr

data = pyreadr.read_r ("births2006.smpl.rda")
print (data.keys())

df = data['births2006.smpl']

df.head(5)


odict_keys(['births2006.idx', 'births2006.smpl'])


DOB_MM  DOB_WK  MAGER TBO_REC WTGAIN SEX APGAR5                  DMEDUC  \
0       9       1     25       2    NaN   F    NaN                    NULL   
1       2       6     28       2     26   M      9      2 years of college   
2       2       2     18       2     25   F      9                    NULL   
3      10       5     21       2      6   M      9                    NULL   
4       7       7     25       1     36   M     10  2 years of high school   

   UPREVIS  ESTGEST DMETH_REC   DPLURAL  DBWT  
0       10       99   Vaginal  1 Single  3800  
1       10       37   Vaginal  1 Single  3625  
2       14       38   Vaginal  1 Single  3650  
3       22       38   Vaginal  1 Single  3045  
4       15       40   Vaginal  1 Single  3827

In [4]:
print (df.columns)

Index(['DOB_MM', 'DOB_WK', 'MAGER', 'TBO_REC', 'WTGAIN', 'SEX', 'APGAR5',
       'DMEDUC', 'UPREVIS', 'ESTGEST', 'DMETH_REC', 'DPLURAL', 'DBWT'],
      dtype='object')


In [1]:
import numpy as np
a = np.array([[1, 2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
print (a[1::2][0][2])

7
